/**
 * Objective 3 — The Parser
 * Reads lcov.info (generated by Jest, Vitest, Istanbul, nyc, or any C1 tool)
 * and converts it to the shared CoverageReport JSON format defined in schema.js.
 *
 * File: core-server/src/lcov-parser.js
 *
 * Usage:
 *   node lcov-parser.js                          # reads coverage/lcov.info
 *   node lcov-parser.js --input path/to/lcov.info --output coverage/report.json
 *
 * API:
 *   import { parseLcov, lcovFileToReport } from './lcov-parser.js'
 */

import { readFile, writeFile } from 'node:fs/promises'
import { existsSync }           from 'node:fs'
import path                     from 'node:path'
import { makeMetric, makeScore, makeCoverageReport } from './schema.js'

// ─── lcov.info record types we care about ─────────────────────────────────────
// SF  — Source File path
// DA  — line Data: DA:<line>,<hits>
// LH  — Lines Hit (covered count)
// LF  — Lines Found (total count)
// FNF — Functions Found
// FNH — Functions Hit
// BRF — Branches Found
// BRH — Branches Hit
// end_of_record

/**
 * Parse raw lcov.info text into an array of per-file objects.
 * Each object matches the `FileEntry` shape from schema.js.
 *
 * @param {string} lcovText  - Full contents of lcov.info
 * @param {string} [rootDir] - Strip this prefix from file paths
 * @returns {import('./schema.js').FileEntry[]}
 */
export function parseLcov(lcovText, rootDir = process.cwd()) {
  const files = []
  let current = null

  for (const rawLine of lcovText.split('\n')) {
    const line = rawLine.trim()
    if (!line) continue

    if (line.startsWith('SF:')) {
      // Start of a new file record
      const absPath = line.slice(3).trim()
      const relPath = path.relative(rootDir, absPath).replace(/\\/g, '/')
      current = {
        path: relPath,
        // Accumulators — filled in as we parse DA/FN/BR records
        _linesTotal:   0,
        _linesCovered: 0,
        _fnTotal:      0,
        _fnCovered:    0,
        _brTotal:      0,
        _brCovered:    0,
        _uncoveredLines: [],
        // Prefer the explicit LF/LH/FNF/FNH/BRF/BRH totals when available
        _hasLF: false, _hasLH: false,
        _hasFNF: false, _hasFNH: false,
        _hasBRF: false, _hasBRH: false,
      }
      continue
    }

    if (!current) continue

    // DA:<lineNumber>,<executionCount>
    if (line.startsWith('DA:')) {
      const [lineNo, hits] = line.slice(3).split(',').map(Number)
      current._linesTotal++
      if (hits > 0) {
        current._linesCovered++
      } else {
        current._uncoveredLines.push(lineNo)
      }
      continue
    }

    // LF:<total lines>
    if (line.startsWith('LF:')) {
      current._linesTotal = parseInt(line.slice(3), 10)
      current._hasLF = true
      continue
    }

    // LH:<covered lines>
    if (line.startsWith('LH:')) {
      current._linesCovered = parseInt(line.slice(3), 10)
      current._hasLH = true
      continue
    }

    // FNF:<total functions>
    if (line.startsWith('FNF:')) {
      current._fnTotal = parseInt(line.slice(4), 10)
      current._hasFNF = true
      continue
    }

    // FNH:<covered functions>
    if (line.startsWith('FNH:')) {
      current._fnCovered = parseInt(line.slice(4), 10)
      current._hasFNH = true
      continue
    }

    // BRF:<total branches>
    if (line.startsWith('BRF:')) {
      current._brTotal = parseInt(line.slice(4), 10)
      current._hasBRF = true
      continue
    }

    // BRH:<covered branches>
    if (line.startsWith('BRH:')) {
      current._brCovered = parseInt(line.slice(4), 10)
      current._hasBRH = true
      continue
    }

    if (line === 'end_of_record') {
      if (!current) continue

      const lines      = makeMetric(current._linesTotal,   current._linesCovered)
      // Statements in lcov map to lines (lcov doesn't distinguish statements)
      const statements = makeMetric(current._linesTotal,   current._linesCovered)
      const functions  = makeMetric(current._fnTotal,      current._fnCovered)
      const branches   = makeMetric(current._brTotal,      current._brCovered)

      /** @type {import('./schema.js').FileEntry} */
      const entry = {
        path:           current.path,
        lines,
        statements,
        functions,
        branches,
        score:          makeScore({ lines, statements, functions, branches }),
        uncoveredLines: current._uncoveredLines,
      }

      files.push(entry)
      current = null
    }
  }

  return files
}

/**
 * Full pipeline: read lcov.info → parse → wrap in CoverageReport schema.
 *
 * @param {string} lcovPath - Path to lcov.info
 * @param {string} rootDir  - Project root for path normalisation
 * @returns {Promise<import('./schema.js').CoverageReport>}
 */
export async function lcovFileToReport(lcovPath, rootDir = process.cwd()) {
  if (!existsSync(lcovPath)) {
    throw new Error(`lcov file not found: ${lcovPath}`)
  }

  const text  = await readFile(lcovPath, 'utf-8')
  const files = parseLcov(text, rootDir)

  if (files.length === 0) {
    console.warn('[lcov-parser] no file records found — is the lcov.info empty?')
  }

  return makeCoverageReport(files)
}

// ─── CLI entrypoint ───────────────────────────────────────────────────────────
async function main() {
  const args = process.argv.slice(2)
  const get  = (flag) => {
    const i = args.indexOf(flag)
    return i !== -1 ? args[i + 1] : null
  }

  const inputPath  = get('--input')  ?? path.resolve(process.cwd(), 'coverage/lcov.info')
  const outputPath = get('--output') ?? path.resolve(process.cwd(), 'coverage/report.json')
  const rootDir    = get('--root')   ?? process.cwd()

  console.log(`[lcov-parser] reading  ${inputPath}`)
  console.log(`[lcov-parser] root     ${rootDir}`)

  const report = await lcovFileToReport(inputPath, rootDir)

  await writeFile(outputPath, JSON.stringify(report, null, 2), 'utf-8')

  console.log(`[lcov-parser] wrote    ${outputPath}`)
  console.log(`[lcov-parser] files    ${report.files.length}`)
  console.log(`[lcov-parser] lines    ${report.summary.lines.pct}%`)
  console.log(`[lcov-parser] branches ${report.summary.branches.pct}%`)
  console.log(`[lcov-parser] functions ${report.summary.functions.pct}%`)
}

// Run when executed directly: node lcov-parser.js
if (process.argv[1] && process.argv[1].endsWith('lcov-parser.js')) {
  main().catch((err) => {
    console.error('[lcov-parser] error:', err.message)
    process.exit(1)
  })
}