import express from 'express';
import cors from 'cors';
import fs from 'fs';
import path from 'path';
import { parseLcov } from './services/parser';

const app = express();
const port = 3000;

app.use(cors());

// Path to the coverage file generated by Vitest in demo-app
const LCOV_PATH = path.join(__dirname, '../demo-app/coverage/lcov.info');

interface CoverageFile {
  name: string;
  linesCount: number;
  linesHit: number;
  coverage: number;
}

interface CoverageData {
  global: number;
  files: CoverageFile[];
}

let currentCoverage: CoverageData = {
  global: 0,
  files: []
};

function updateCoverage() {
  try {
    if (fs.existsSync(LCOV_PATH)) {
      const lcovData = fs.readFileSync(LCOV_PATH, 'utf-8');
      currentCoverage = parseLcov(lcovData);
      console.log('Updated coverage data from lcov.info');
    } else {
      console.log('Waiting for lcov.info to be generated...');
    }
  } catch (error) {
    console.error('Error reading lcov.info:', error);
  }
}

// Initial update
updateCoverage();

// Watch for changes in the coverage directory
if (fs.existsSync(path.dirname(LCOV_PATH))) {
    fs.watch(path.dirname(LCOV_PATH), (eventType, filename) => {
        if (filename === 'lcov.info') {
            updateCoverage();
        }
    });
}

app.get('/', (req, res) => {
  res.send('Coverage Lens Core Server');
});

app.get('/coverage', (req, res) => {
  res.json(currentCoverage);
});

app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}`);
});
